### ISSUE TITLE
abundance data

### ISSUE THREAD

**Issue by cmtucker** [Rekyt/funrar#11]
How are different types of abundance data dealt with currently in outlier? Does it matter if the data is count data, relative abundance data, % cover, etc?

**Comment by Rekyt** [comment]
For the moment we're only considering people submitting relative abundance data or % cover (as long as it is between 0 and 1). But we're not doing any check on it.

**Comment by cmtucker** [comment]
Percent cover data can sum to greater than 100%. Is that problem?

**Comment by Rekyt** [comment]
Well, it would work for Distinctiveness because it's standardized, but I'm not sure about scarcity...

**Comment by Rekyt** [comment]
We should think better about this and try to warn the users in the cases they use other things than relative abundances
