### ISSUE TITLE
Matrices-Dataframes

### ISSUE THREAD

**Issue by cmtucker** [Rekyt/funrar#14]
For the functions, is it possible to add either a check for the incorrect data type that returns a warning (e.g. pres_matrix is a dataframe, must be a matrix); or a check that automatically converts df -> matrix and continues the calculations?
Currently no informative error shows up if you input a data.frame, just something like "Error in pres_matrix %*% dist_matrix :   requires numeric/complex matrix/vector arguments"
I imagine this would be a common issue.

**Comment by Rekyt** [comment]
Yep, and for the moment some functions have a bunch of tests like `table_distinctiveness()` but some others don't. So we should may be add internal functions to check data types and return errors.
Like for normal functions:
- check pres_matrix is `matrix`
- check dist_matrix is a `matrix` and is a square matrix
- check at least some species in `dist_matrix` are in `pres_matrix` and take this subset

Other ideas ?

**Comment by Rekyt** [comment]
See branch 'more_tests' commits  2ad2eec ... 19554c8 implement automated input checks
