### ISSUE TITLE
Create a hex sticker

### ISSUE THREAD

**Issue by Rekyt** [Rekyt/funrar#51]
It's too bad that funrar doesn't have a hex sticker.
Maybe we could use a similar template as [funbiogeo](https://github.com/FRBCesab/funbiogeo) or [fundiversity](https://github.com/funecology/fundiversity) by underlining species at the edge of the functional trait space.

Maybe with the default included dataset?

**Comment by pierredenelle** [comment]
![logo_funrar](https://github.com/Rekyt/funrar/assets/15929897/5f0ca6f7-c33c-40c0-827c-f99f4aa86535)

?

**Comment by Rekyt** [comment]
Oh woah! Thanks for the proposal 😁 
I thought about doing a similar thing to fundiversity: https://github.com/funecology/fundiversity/blob/main/inst/hexlogo/fundiversity-sticker.R
Like creating it from R, using the functional space we provide in the package and exactly like you did, highlighting the most distinct species.

**Comment by Rekyt** [comment]
Woops, I realized we don't have data included in the package.
Either we use the aravo dataset for the sticker or the mammals of Americas.

**Comment by Rekyt** [comment]
What do you think of this?
![logo](https://github.com/Rekyt/funrar/assets/5593751/61fb0ac1-1754-4b90-9bef-12b18d6e2682)

**Comment by pierredenelle** [comment]
Great! Not the biggest fan of the black background but at least it resembles the logo of funbiogeo. 

And regarding the data, we could provide a dataset together with the package. If possible, the mammal dataset used in the paper.

**Comment by Rekyt** [comment]
Should I make it look like `fundiversity` ones then?
Or choose another color?

**Comment by Rekyt** [comment]
If you want to tweak the code, you can on the [funrar/hex_logo](https://github.com/Rekyt/funrar/tree/hex_logo) branch

**Comment by pierredenelle** [comment]
I would do it like `fundiversity` indeed. But it is a matter of taste, both are legit.

**Comment by Rekyt** [comment]
Hum...
![logo](https://github.com/Rekyt/funrar/assets/5593751/2fe3a717-f7ed-4523-ac62-1156d0b730e3)

or 

![logo](https://github.com/Rekyt/funrar/assets/5593751/b9198d71-cec3-4a96-a84f-462f988bfd99)

I quite like the second option

**Comment by pierredenelle** [comment]
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQr0dgvCbiyKiFj0N2njc4dPB6ta4tzf2dWFKSy91GFqA&s
^^

**Comment by pierredenelle** [comment]
Joke aside, I also prefer the second.

**Comment by Rekyt** [comment]
Lighter blue? Darker blue? Purple rather than blue?

What about this one:

![logo](https://github.com/Rekyt/funrar/assets/5593751/d7c07627-be96-4464-8b5e-a4ad275cfe88)

**Comment by pierredenelle** [comment]
Nice. Maybe a lighter blue. RGBA 96dcf5ff ?

**Comment by Rekyt** [comment]
I tried with another color, I really can't decide
![logo](https://github.com/Rekyt/funrar/assets/5593751/48198311-798c-4f24-ba24-9cdf58da7d5e)

**Comment by pierredenelle** [comment]
This one is great, keep it!

**Comment by Rekyt** [comment]
Last trial (changed the border color)
![logo](https://github.com/Rekyt/funrar/assets/5593751/f4eed7ca-3fee-4b97-be54-1088560ed85b)

**Comment by pierredenelle** [comment]
I like both, as you wish ;)

**Comment by Rekyt** [comment]
Or same color as the text?
![logo](https://github.com/Rekyt/funrar/assets/5593751/994e6ef1-a2f4-427d-90d9-3d1f76ca8d4e)
